# Generated by Django 2.2.4 on 2019-08-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
